# Create NumPy Arrays

In [6]:
import numpy as np

In [2]:
nums = [1,2,3,4]

In [3]:
nums = np.array(nums)

In [5]:
nums

array([1, 2, 3, 4])

## 2D Array

In [7]:
nums = [[1,2,3,4],[5,6,7,8]]

In [8]:
nums = np.array(nums)

In [9]:
nums

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 3D Arrays

In [10]:
nums = [[1,2,3,4],[5,6,7,8],[9,7,5,4]]

In [11]:
nums = np.array(nums)

In [12]:
nums

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 5, 4]])

In [14]:
nums.shape

(3, 4)